/**
 * Interlinked mock dataset backing every /api route until the Go backend exists.
 * Dates are computed relative to "now" so today-centric views always have data.
 * Shapes are the API contract — see docs/api-contract.md.
 */

const HOUR = 60 * 60 * 1000
const DAY = 24 * HOUR

const hoursAgo = (n: number) => new Date(Date.now() - n * HOUR).toISOString()
const daysAgo = (n: number) => new Date(Date.now() - n * DAY).toISOString()
const daysFromNow = (n: number) => new Date(Date.now() + n * DAY).toISOString()

const dayAt = (dayOffset: number, hours: number, minutes = 0) => {
  const d = new Date()
  d.setDate(d.getDate() + dayOffset)
  d.setHours(hours, minutes, 0, 0)
  return d.toISOString()
}

export const staff: StaffMember[] = [
  {
    id: "stf_001",
    name: "Ray Delgado",
    role: "owner",
    title: "General Manager",
    avatarUrl: "",
    activeTasks: 0,
    capacity: 0,
    completedMtd: 0,
    revenueMtd: 0,
  },
  {
    id: "stf_002",
    name: "Sarah Jenner",
    role: "mechanic",
    title: "Senior Technician",
    avatarUrl: "",
    activeTasks: 6,
    capacity: 8,
    completedMtd: 21,
    revenueMtd: 24800,
  },
  {
    id: "stf_003",
    name: "Nikola Reyes",
    role: "mechanic",
    title: "Technician",
    avatarUrl: "",
    activeTasks: 2,
    capacity: 8,
    completedMtd: 16,
    revenueMtd: 19200,
  },
  {
    id: "stf_004",
    name: "Jess Kim",
    role: "mechanic",
    title: "Apprentice Technician",
    avatarUrl: "",
    activeTasks: 2,
    capacity: 6,
    completedMtd: 11,
    revenueMtd: 14100,
  },
]

export const customers: Customer[] = [
  {
    id: "cus_001",
    name: "Jane Dorsey",
    email: "jane.dorsey@gmail.com",
    phone: "+1 512 555 0142",
    avatarUrl: "",
    status: "active",
    location: "Austin, TX",
    tags: ["repeat"],
    lastInteraction: { type: "phone_call", at: hoursAgo(2) },
    lifetimeValue: 4250,
    vehicleIds: ["veh_001"],
    createdAt: daysAgo(410),
  },
  {
    id: "cus_002",
    name: "James Okafor",
    email: "james.okafor@gmail.com",
    phone: "+1 512 555 0187",
    avatarUrl: "",
    status: "new",
    location: "Round Rock, TX",
    tags: [],
    lastInteraction: { type: "form_submitted", at: daysAgo(1) },
    lifetimeValue: 0,
    vehicleIds: ["veh_002"],
    createdAt: daysAgo(1),
  },
  {
    id: "cus_003",
    name: "Marla Chen",
    email: "marla.chen@gmail.com",
    phone: "+1 512 555 0233",
    avatarUrl: "",
    status: "follow_up",
    location: "Austin, TX",
    tags: ["fleet"],
    lastInteraction: { type: "estimate_sent", at: daysAgo(3) },
    lifetimeValue: 8900,
    vehicleIds: ["veh_003"],
    createdAt: daysAgo(720),
  },
  {
    id: "cus_004",
    name: "Bill Kovac",
    email: "bill.kovac@gmail.com",
    phone: "+1 512 555 0361",
    avatarUrl: "",
    status: "archived",
    location: "Pflugerville, TX",
    tags: [],
    lastInteraction: { type: "no_activity", at: daysAgo(14) },
    lifetimeValue: 640,
    vehicleIds: ["veh_004"],
    createdAt: daysAgo(900),
  },
  {
    id: "cus_005",
    name: "Robert Trask",
    email: "robert.trask@gmail.com",
    phone: "+1 512 555 0419",
    avatarUrl: "",
    status: "new",
    location: "Cedar Park, TX",
    tags: [],
    lastInteraction: { type: "form_submitted", at: daysAgo(14) },
    lifetimeValue: 0,
    vehicleIds: ["veh_005"],
    createdAt: daysAgo(14),
  },
  {
    id: "cus_006",
    name: "Laura Whitfield",
    email: "laura.whitfield@gmail.com",
    phone: "+1 512 555 0505",
    avatarUrl: "",
    status: "follow_up",
    location: "Austin, TX",
    tags: [],
    lastInteraction: { type: "estimate_sent", at: daysAgo(21) },
    lifetimeValue: 3120,
    vehicleIds: ["veh_006"],
    createdAt: daysAgo(530),
  },
  {
    id: "cus_007",
    name: "Miguel Santos",
    email: "miguel.santos@gmail.com",
    phone: "+1 512 555 0668",
    avatarUrl: "",
    status: "active",
    location: "Buda, TX",
    tags: ["repeat", "fleet"],
    lastInteraction: { type: "visit", at: daysAgo(1) },
    lifetimeValue: 11400,
    vehicleIds: ["veh_007", "veh_009"],
    createdAt: daysAgo(1100),
  },
  {
    id: "cus_008",
    name: "Emily Marr",
    email: "emily.marr@gmail.com",
    phone: "+1 512 555 0714",
    avatarUrl: "",
    status: "active",
    location: "Austin, TX",
    tags: [],
    lastInteraction: { type: "email", at: hoursAgo(4) },
    lifetimeValue: 1870,
    vehicleIds: ["veh_008"],
    createdAt: daysAgo(260),
  },
]

export const vehicles: Vehicle[] = [
  {
    id: "veh_001",
    customerId: "cus_001",
    make: "Toyota",
    model: "RAV4",
    year: 2021,
    vin: "2T3P1RFV8MC143921",
    licensePlate: "GPR-402",
    mileage: 41250,
    engine: "2.5L I4",
    transmission: "Automatic",
    fuelType: "gasoline",
    photoUrl: "",
    status: "ready",
    listPrice: null,
    lastServiceAt: daysAgo(1),
  },
  {
    id: "veh_002",
    customerId: "cus_002",
    make: "Honda",
    model: "Civic",
    year: 2019,
    vin: "19XFC2F59KE028461",
    licensePlate: "KBT-112",
    mileage: 62830,
    engine: "1.5L Turbo I4",
    transmission: "CVT",
    fuelType: "gasoline",
    photoUrl: "",
    status: "in_shop",
    listPrice: null,
    lastServiceAt: daysAgo(190),
  },
  {
    id: "veh_003",
    customerId: "cus_003",
    make: "Tesla",
    model: "Model 3",
    year: 2022,
    vin: "5YJ3E1EA8NF302175",
    licensePlate: "EVX-889",
    mileage: 28400,
    engine: "Dual Motor",
    transmission: "Single-speed",
    fuelType: "electric",
    photoUrl: "",
    status: "in_shop",
    listPrice: null,
    lastServiceAt: daysAgo(3),
  },
  {
    id: "veh_004",
    customerId: "cus_004",
    make: "Ford",
    model: "F-150",
    year: 2015,
    vin: "1FTEW1EF6FFB74210",
    licensePlate: "TRK-951",
    mileage: 128900,
    engine: "5.0L V8",
    transmission: "Automatic",
    fuelType: "gasoline",
    photoUrl: "",
    status: "active",
    listPrice: null,
    lastServiceAt: daysAgo(8),
  },
  {
    id: "veh_005",
    customerId: "cus_005",
    make: "BMW",
    model: "X5",
    year: 2020,
    vin: "5UXCR6C09L9C33482",
    licensePlate: "BXV-207",
    mileage: 54120,
    engine: "3.0L I6 Turbo",
    transmission: "Automatic",
    fuelType: "gasoline",
    photoUrl: "",
    status: "in_shop",
    listPrice: null,
    lastServiceAt: hoursAgo(5),
  },
  {
    id: "veh_006",
    customerId: "cus_006",
    make: "Audi",
    model: "A4",
    year: 2018,
    vin: "WAUENAF47JA027390",
    licensePlate: "ADQ-664",
    mileage: 71600,
    engine: "2.0L TFSI",
    transmission: "S tronic",
    fuelType: "gasoline",
    photoUrl: "",
    status: "in_shop",
    listPrice: null,
    lastServiceAt: daysAgo(21),
  },
  {
    id: "veh_007",
    customerId: "cus_007",
    make: "Jeep",
    model: "Wrangler",
    year: 2017,
    vin: "1C4BJWDG5HL512743",
    licensePlate: "WR-998",
    mileage: 88300,
    engine: "3.6L V6",
    transmission: "Manual",
    fuelType: "gasoline",
    photoUrl: "",
    status: "ready",
    listPrice: null,
    lastServiceAt: hoursAgo(3),
  },
  {
    id: "veh_008",
    customerId: "cus_008",
    make: "Kia",
    model: "Sportage Hybrid",
    year: 2023,
    vin: "KNDPUCDG8P7031264",
    licensePlate: "HYB-330",
    mileage: 12400,
    engine: "1.6L Turbo Hybrid",
    transmission: "Automatic",
    fuelType: "hybrid",
    photoUrl: "",
    status: "in_shop",
    listPrice: null,
    lastServiceAt: daysAgo(45),
  },
  {
    id: "veh_009",
    customerId: "cus_007",
    make: "Subaru",
    model: "Outback",
    year: 2016,
    vin: "4S4BSANC5G3204118",
    licensePlate: "OBK-118",
    mileage: 103700,
    engine: "2.5L H4",
    transmission: "CVT",
    fuelType: "gasoline",
    photoUrl: "",
    status: "in_shop",
    listPrice: null,
    lastServiceAt: daysAgo(365),
  },
  {
    id: "veh_010",
    customerId: null,
    make: "Mercedes-Benz",
    model: "C300",
    year: 2022,
    vin: "W1KWF8DB1NR104563",
    licensePlate: "DLR-014",
    mileage: 19800,
    engine: "2.0L I4 Turbo",
    transmission: "Automatic",
    fuelType: "gasoline",
    photoUrl: "",
    status: "for_sale",
    listPrice: 41900,
    lastServiceAt: daysAgo(12),
  },
]

export const workOrders: WorkOrder[] = [
  {
    id: "wo_482",
    number: "WO-0482",
    customerId: "cus_005",
    vehicleId: "veh_005",
    assignedMechanicId: "stf_002",
    status: "diagnostics",
    priority: "high",
    serviceType: "engine_diagnostic",
    title: "Check engine light — cylinder misfire",
    description:
      "Customer reports rough idle and intermittent check engine light. Pull codes, compression test cylinders 1-6.",
    progressPct: 40,
    lineItems: [
      { description: "Diagnostic labor (2h)", qty: 2, unitPrice: 120 },
      { description: "Ignition coil (est.)", qty: 2, unitPrice: 95 },
    ],
    estimateTotal: 1240,
    scheduledAt: dayAt(0, 9, 30),
    completedAt: null,
    notes: [
      {
        id: "won_001",
        authorId: "stf_002",
        body: "Codes P0301/P0303. Swapped coils to confirm — misfire follows coil. Waiting on customer approval for parts.",
        at: hoursAgo(3),
      },
    ],
    createdAt: daysAgo(1),
  },
  {
    id: "wo_483",
    number: "WO-0483",
    customerId: "cus_002",
    vehicleId: "veh_002",
    assignedMechanicId: null,
    status: "intake",
    priority: "normal",
    serviceType: "brake_system",
    title: "Front brake pads + rotors",
    description: "Grinding noise on braking. Inspect pads, rotors, calipers.",
    progressPct: 0,
    lineItems: [
      { description: "Front pads (set)", qty: 1, unitPrice: 89 },
      { description: "Front rotors", qty: 2, unitPrice: 74 },
      { description: "Labor (1.5h)", qty: 1, unitPrice: 180 },
    ],
    estimateTotal: 417,
    scheduledAt: dayAt(0, 9, 0),
    completedAt: null,
    notes: [],
    createdAt: daysAgo(1),
  },
  {
    id: "wo_484",
    number: "WO-0484",
    customerId: "cus_001",
    vehicleId: "veh_001",
    assignedMechanicId: "stf_003",
    status: "ready",
    priority: "normal",
    serviceType: "brake_system",
    title: "Brake pad replacement",
    description: "Rear pads at 2mm. Replace and bed in.",
    progressPct: 100,
    lineItems: [
      { description: "Rear pads (set)", qty: 1, unitPrice: 96 },
      { description: "Labor (1.2h)", qty: 1, unitPrice: 144 },
      { description: "Brake fluid flush", qty: 1, unitPrice: 210 },
    ],
    estimateTotal: 450,
    scheduledAt: dayAt(-1, 14, 0),
    completedAt: hoursAgo(4),
    notes: [
      {
        id: "won_002",
        authorId: "stf_003",
        body: "Done and test-driven. Pickup scheduled for 1:30 PM — automated SMS reminder sent to customer.",
        at: hoursAgo(4),
      },
    ],
    createdAt: daysAgo(2),
  },
  {
    id: "wo_485",
    number: "WO-0485",
    customerId: "cus_006",
    vehicleId: "veh_006",
    assignedMechanicId: "stf_004",
    status: "diagnostics",
    priority: "normal",
    serviceType: "electrical",
    title: "Battery drain trace",
    description:
      "Battery dead after 2 days parked. Parasitic draw test across fuse boxes.",
    progressPct: 25,
    lineItems: [{ description: "Electrical diagnostic (2h)", qty: 2, unitPrice: 120 }],
    estimateTotal: 240,
    scheduledAt: daysFromNow(7),
    completedAt: null,
    notes: [],
    createdAt: daysAgo(2),
  },
  {
    id: "wo_486",
    number: "WO-0486",
    customerId: "cus_003",
    vehicleId: "veh_003",
    assignedMechanicId: "stf_002",
    status: "in_repair",
    priority: "high",
    serviceType: "general_repair",
    title: "Front suspension bushings",
    description: "Clunk over bumps. Replace front control arm bushings.",
    progressPct: 60,
    lineItems: [
      { description: "Control arm bushings (pair)", qty: 2, unitPrice: 340 },
      { description: "Labor (4h)", qty: 4, unitPrice: 120 },
      { description: "Alignment", qty: 1, unitPrice: 1700 },
    ],
    estimateTotal: 2860,
    scheduledAt: dayAt(1, 10, 30),
    completedAt: null,
    notes: [
      {
        id: "won_003",
        authorId: "stf_002",
        body: "Left side done. Right bushing pressed in tomorrow morning, then alignment.",
        at: hoursAgo(6),
      },
    ],
    createdAt: daysAgo(3),
  },
  {
    id: "wo_487",
    number: "WO-0487",
    customerId: "cus_004",
    vehicleId: "veh_004",
    assignedMechanicId: "stf_003",
    status: "delivered",
    priority: "low",
    serviceType: "maintenance",
    title: "Oil change + filters",
    description: "Full synthetic oil change, air + cabin filters.",
    progressPct: 100,
    lineItems: [
      { description: "Full synthetic oil (7qt)", qty: 1, unitPrice: 89 },
      { description: "Filters", qty: 1, unitPrice: 58 },
      { description: "Labor (0.8h)", qty: 1, unitPrice: 165 },
    ],
    estimateTotal: 312,
    scheduledAt: daysAgo(5),
    completedAt: daysAgo(5),
    notes: [],
    createdAt: daysAgo(9),
  },
  {
    id: "wo_488",
    number: "WO-0488",
    customerId: "cus_007",
    vehicleId: "veh_007",
    assignedMechanicId: "stf_004",
    status: "ready",
    priority: "normal",
    serviceType: "tire_rotation",
    title: "Tire rotation & balance",
    description: "Rotate + road-force balance all four.",
    progressPct: 100,
    lineItems: [{ description: "Rotation & balance", qty: 1, unitPrice: 180 }],
    estimateTotal: 180,
    scheduledAt: dayAt(0, 13, 30),
    completedAt: hoursAgo(3),
    notes: [],
    createdAt: daysAgo(1),
  },
  {
    id: "wo_489",
    number: "WO-0489",
    customerId: "cus_008",
    vehicleId: "veh_008",
    assignedMechanicId: "stf_002",
    status: "waiting_parts",
    priority: "normal",
    serviceType: "electrical",
    title: "Infotainment wiring harness",
    description:
      "Screen blackouts. Harness on backorder — ETA 3 business days.",
    progressPct: 55,
    lineItems: [
      { description: "Harness (OEM)", qty: 1, unitPrice: 410 },
      { description: "Labor (2.5h)", qty: 1, unitPrice: 300 },
    ],
    estimateTotal: 710,
    scheduledAt: daysFromNow(2),
    completedAt: null,
    notes: [
      {
        id: "won_004",
        authorId: "stf_002",
        body: "Part ordered from distributor. Customer notified automatically by email.",
        at: daysAgo(1),
      },
    ],
    createdAt: daysAgo(4),
  },
  {
    id: "wo_490",
    number: "WO-0490",
    customerId: "cus_007",
    vehicleId: "veh_009",
    assignedMechanicId: null,
    status: "intake",
    priority: "low",
    serviceType: "inspection",
    title: "Annual state inspection",
    description: "Standard annual inspection.",
    progressPct: 0,
    lineItems: [{ description: "State inspection", qty: 1, unitPrice: 25 }],
    estimateTotal: 25,
    scheduledAt: dayAt(0, 11, 30),
    completedAt: null,
    notes: [],
    createdAt: hoursAgo(20),
  },
  {
    id: "wo_491",
    number: "WO-0491",
    customerId: "cus_006",
    vehicleId: "veh_006",
    assignedMechanicId: "stf_003",
    status: "delivered",
    priority: "normal",
    serviceType: "general_repair",
    title: "Valve cover gasket",
    description: "Oil seep at valve cover. Replaced gasket, cleaned block.",
    progressPct: 100,
    lineItems: [
      { description: "Valve cover gasket", qty: 1, unitPrice: 65 },
      { description: "Labor (2.4h)", qty: 1, unitPrice: 288 },
      { description: "Degrease + inspect", qty: 1, unitPrice: 287 },
    ],
    estimateTotal: 640,
    scheduledAt: daysAgo(22),
    completedAt: daysAgo(21),
    notes: [],
    createdAt: daysAgo(23),
  },
]

export const appointments: Appointment[] = [
  {
    id: "app_001",
    customerId: "cus_002",
    vehicleId: "veh_002",
    workOrderId: "wo_483",
    type: "drop_off",
    scheduledAt: dayAt(0, 9, 0),
    durationMin: 15,
    status: "confirmed",
  },
  {
    id: "app_002",
    customerId: "cus_005",
    vehicleId: "veh_005",
    workOrderId: "wo_482",
    type: "service",
    scheduledAt: dayAt(0, 9, 30),
    durationMin: 120,
    status: "confirmed",
  },
  {
    id: "app_003",
    customerId: "cus_007",
    vehicleId: "veh_009",
    workOrderId: "wo_490",
    type: "inspection",
    scheduledAt: dayAt(0, 11, 30),
    durationMin: 45,
    status: "confirmed",
  },
  {
    id: "app_004",
    customerId: "cus_001",
    vehicleId: "veh_001",
    workOrderId: "wo_484",
    type: "pickup",
    scheduledAt: dayAt(0, 13, 30),
    durationMin: 15,
    status: "confirmed",
  },
  {
    id: "app_005",
    customerId: "cus_007",
    vehicleId: "veh_007",
    workOrderId: "wo_488",
    type: "pickup",
    scheduledAt: dayAt(0, 15, 0),
    durationMin: 15,
    status: "pending",
  },
  {
    id: "app_006",
    customerId: "cus_003",
    vehicleId: "veh_003",
    workOrderId: "wo_486",
    type: "service",
    scheduledAt: dayAt(1, 10, 30),
    durationMin: 240,
    status: "pending",
  },
  {
    id: "app_007",
    customerId: "cus_008",
    vehicleId: "veh_008",
    workOrderId: "wo_489",
    type: "drop_off",
    scheduledAt: dayAt(2, 8, 30),
    durationMin: 15,
    status: "pending",
  },
  {
    id: "app_008",
    customerId: "cus_006",
    vehicleId: "veh_006",
    workOrderId: "wo_485",
    type: "service",
    scheduledAt: dayAt(7, 9, 0),
    durationMin: 180,
    status: "confirmed",
  },
]

export const invoices: Invoice[] = [
  {
    id: "inv_001",
    workOrderId: "wo_484",
    number: "INV-2026-042",
    kind: "invoice",
    amount: 450,
    status: "pending",
    recipient: "Jane Dorsey",
    issuedAt: hoursAgo(4),
    dueAt: daysFromNow(14),
  },
  {
    id: "inv_002",
    workOrderId: "wo_488",
    number: "INV-2026-041",
    kind: "invoice",
    amount: 180,
    status: "sent",
    recipient: "Miguel Santos",
    issuedAt: hoursAgo(3),
    dueAt: daysFromNow(14),
  },
  {
    id: "inv_003",
    workOrderId: "wo_487",
    number: "INV-2026-040",
    kind: "invoice",
    amount: 312,
    status: "paid",
    recipient: "Bill Kovac",
    issuedAt: daysAgo(8),
    dueAt: daysAgo(8),
  },
  {
    id: "inv_004",
    workOrderId: "wo_491",
    number: "INV-2026-039",
    kind: "invoice",
    amount: 640,
    status: "overdue",
    recipient: "Laura Whitfield",
    issuedAt: daysAgo(21),
    dueAt: daysAgo(7),
  },
  {
    id: "inv_005",
    workOrderId: "wo_482",
    number: "EST-2026-015",
    kind: "estimate",
    amount: 1240,
    status: "draft",
    recipient: "Robert Trask",
    issuedAt: hoursAgo(3),
    dueAt: null,
  },
  {
    id: "inv_006",
    workOrderId: "wo_486",
    number: "EST-2026-014",
    kind: "estimate",
    amount: 2860,
    status: "sent",
    recipient: "Marla Chen",
    issuedAt: daysAgo(3),
    dueAt: null,
  },
]

export const notifications: AppNotification[] = [
  {
    id: "not_001",
    kind: "reminder",
    urgency: "urgent",
    title: "Pickup reminder sent — Jane Dorsey",
    body: "Automated SMS sent for RAV4 pickup at 1:30 PM. Customer requested a callback about part ETA.",
    relatedCustomerId: "cus_001",
    relatedWorkOrderId: "wo_484",
    createdAt: hoursAgo(2),
    read: false,
  },
  {
    id: "not_002",
    kind: "system",
    urgency: "normal",
    title: "Parts backorder — WO-0489",
    body: "Infotainment harness ETA moved to 3 business days. Schedule impact flagged.",
    relatedCustomerId: "cus_008",
    relatedWorkOrderId: "wo_489",
    createdAt: hoursAgo(5),
    read: false,
  },
  {
    id: "not_003",
    kind: "payment",
    urgency: "urgent",
    title: "Invoice overdue — INV-2026-039",
    body: "Laura Whitfield's invoice for $640 is 7 days past due. Automated email reminder sent.",
    relatedCustomerId: "cus_006",
    relatedWorkOrderId: "wo_491",
    createdAt: daysAgo(1),
    read: false,
  },
  {
    id: "not_004",
    kind: "reminder",
    urgency: "normal",
    title: "Appointment confirmation pending",
    body: "Marla Chen has not confirmed tomorrow's 10:30 AM service. Reminder scheduled for 5 PM.",
    relatedCustomerId: "cus_003",
    relatedWorkOrderId: "wo_486",
    createdAt: hoursAgo(7),
    read: true,
  },
  {
    id: "not_005",
    kind: "system",
    urgency: "low",
    title: "New customer form submitted",
    body: "James Okafor submitted the intake form for a 2019 Honda Civic (brake noise).",
    relatedCustomerId: "cus_002",
    relatedWorkOrderId: "wo_483",
    createdAt: daysAgo(1),
    read: true,
  },
]

export const reminders: Reminder[] = [
  {
    id: "rem_001",
    urgency: "urgent",
    title: "Jane Dorsey — brake pad repair",
    body: "Customer requested a callback regarding part ETA for her RAV4. Scheduled pickup in 1 hour. Automated SMS reminder sent.",
    channel: "sms",
    relatedCustomerId: "cus_001",
    relatedWorkOrderId: "wo_484",
    sentAt: hoursAgo(2),
  },
  {
    id: "rem_002",
    urgency: "normal",
    title: "Marla Chen — service confirmation",
    body: "Confirmation request for tomorrow 10:30 AM suspension work sent by email.",
    channel: "email",
    relatedCustomerId: "cus_003",
    relatedWorkOrderId: "wo_486",
    sentAt: hoursAgo(7),
  },
  {
    id: "rem_003",
    urgency: "normal",
    title: "Laura Whitfield — overdue invoice",
    body: "Payment reminder for INV-2026-039 ($640) sent by email.",
    channel: "email",
    relatedCustomerId: "cus_006",
    relatedWorkOrderId: "wo_491",
    sentAt: daysAgo(1),
  },
]

export const dashboardStats: DashboardStats = {
  vehiclesInService: {
    value: 12,
    delta: { amount: 3, label: "vs last week", direction: "up" },
  },
  activeCustomers: {
    value: 148,
    delta: { amount: 9, label: "new this month", direction: "up" },
  },
  monthlyRevenue: {
    value: 42600,
    delta: { amount: 8400, label: "this period", direction: "up" },
  },
  bookings: [
    { week: "Week 1", workOrders: 18, appointments: 24 },
    { week: "Week 2", workOrders: 26, appointments: 21 },
    { week: "Week 3", workOrders: 22, appointments: 30 },
    { week: "Week 4", workOrders: 31, appointments: 27 },
  ],
  serviceRequests: [
    { serviceType: "engine_diagnostic", pct: 32 },
    { serviceType: "brake_system", pct: 24 },
    { serviceType: "general_repair", pct: 19 },
    { serviceType: "electrical", pct: 16 },
    { serviceType: "tire_rotation", pct: 9 },
  ],
  revenueTrend: [
    { week: "Week 1", revenue: 8900 },
    { week: "Week 2", revenue: 10400 },
    { week: "Week 3", revenue: 9600 },
    { week: "Week 4", revenue: 13700 },
  ],
}

export const activity: ActivityEntry[] = [
  {
    id: "act_001",
    customerId: "cus_001",
    vehicleId: "veh_001",
    type: "service",
    status: "complete",
    value: 450,
    at: hoursAgo(4),
  },
  {
    id: "act_002",
    customerId: "cus_007",
    vehicleId: "veh_007",
    type: "service",
    status: "complete",
    value: 180,
    at: hoursAgo(3),
  },
  {
    id: "act_003",
    customerId: "cus_005",
    vehicleId: "veh_005",
    type: "service",
    status: "in_progress",
    value: 1240,
    at: hoursAgo(5),
  },
  {
    id: "act_004",
    customerId: "cus_002",
    vehicleId: "veh_002",
    type: "service",
    status: "pending",
    value: 417,
    at: daysAgo(1),
  },
  {
    id: "act_005",
    customerId: "cus_003",
    vehicleId: "veh_003",
    type: "service",
    status: "in_progress",
    value: 2860,
    at: daysAgo(1),
  },
  {
    id: "act_006",
    customerId: "cus_004",
    vehicleId: "veh_004",
    type: "service",
    status: "complete",
    value: 312,
    at: daysAgo(8),
  },
]

export const serviceStats: ServiceStats = {
  appointmentsToday: {
    value: 5,
    delta: { amount: 2, label: "more than yesterday", direction: "up" },
  },
  serviceRevenue: {
    value: 8050,
    delta: { amount: 82, label: "weekly target: 82%", direction: "up" },
  },
  completedServices: {
    value: 38,
    delta: { amount: 4.9, label: "avg satisfaction 4.9/5", direction: "up" },
  },
  pendingRepairs: {
    value: 12,
    delta: { amount: 3, label: "delayed by parts", direction: "down" },
  },
  payments: {
    outstandingTotal: 3210,
    expectedToday: 1410,
    collectionRatePct: 68,
  },
}

export const sessions: Record<"owner" | "mechanic" | "superadmin", Session> = {
  owner: {
    user: { id: "stf_001", name: "Ray Delgado", role: "owner", avatarUrl: "" },
    shop: { id: "shop_001", name: "EngineCare Garage", plan: "team" },
  },
  mechanic: {
    user: {
      id: "stf_002",
      name: "Sarah Jenner",
      role: "mechanic",
      avatarUrl: "",
    },
    shop: { id: "shop_001", name: "EngineCare Garage", plan: "team" },
  },
  superadmin: {
    user: {
      id: "stf_000",
      name: "Platform Admin",
      role: "superadmin",
      avatarUrl: "",
    },
    shop: { id: "shop_001", name: "EngineCare Garage", plan: "team" },
  },
}

let idCounter = 1000
export const nextId = (prefix: string) => `${prefix}_${idCounter++}`
