#!/usr/bin/env node
// scripts/add-slice.mjs
// Usage:
//   pnpm add-slice <name> [--dir=src/features] [--dry]
// Examples:
//   pnpm add-slice user
//   pnpm add-slice shoppingCart --dir=src/modules
//
// Creates: <dir>/<kebab-name>/
//          [name]-actions.ts
//          [name]-initial-state.ts
//          [name]-reducers.ts
//          [name]-selectors.ts
//          [name]-slice.ts
//          [name]-thunks.ts
//          [name]-types.ts
import { constants as fsConstants } from "node:fs";
import { access, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";


function toKebab(str) {
  return str
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase()
}
function toCamel(str) {
  const kebab = toKebab(str)
  return kebab.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
}
function toPascal(str) {
  const c = toCamel(str)
  return c.charAt(0).toUpperCase() + c.slice(1)
}

function parseArgs(argv) {
  const args = argv.slice(2)
  const opts = { dir: "src/redux/", dry: false }
  const name = args.find((a) => !a.startsWith("-"))
  if (!name) {
    console.error("❌ Missing name.\nUsage: pnpm add-slice <name> [--dry]")
    process.exit(1)
  }
  for (const a of args) {
    if (a === "--dry") {
      opts.dry = true
    }
  }

  return { name, opts }
}

function templatesFor(name) {
  const kebab = toKebab(name)
  const camel = toCamel(name)
  const pascal = toPascal(name)
  const sliceName = kebab

  const importInitialState = `import { ${camel}InitialState } from "@/redux/${kebab}/${kebab}-initial-state"`

  return {
    [`${kebab}-actions.ts`]: `// Auto-generated by pnpm addSlice ${name}
// todo: add your actions if needed

`,

    [`${kebab}-initial-state.ts`]: `// Auto-generated by pnpm addSlice ${name}
import { ${pascal}Slice } from "@/redux/${kebab}/${kebab}-types"
import { SliceStatus } from "@/redux/types"

export const ${camel}InitialState: ${pascal}Slice = {
  state: null,
  status: SliceStatus.IDLE,
}

`,

    [`${kebab}-reducers.ts`]: `// Auto-generated by pnpm addSlice ${name}
import { createReducer } from "@reduxjs/toolkit"
${importInitialState}
import { ${pascal}Slice } from "@/redux/${kebab}/${kebab}-types"

export const ${camel}Reducers = createReducer<${pascal}Slice>(
  ${camel}InitialState,
  (builder) => {
    builder.addDefaultCase(() => {})
  }
)

`,

    [`${kebab}-selectors.ts`]: `// Auto-generated by pnpm addSlice ${name}
import { createSelector } from "@reduxjs/toolkit"
import { ${pascal}Slice } from "@/redux/${kebab}/${kebab}-types"
import { RootState } from "@/redux/store"

// todo: add the slice in the RootState @/redux/slices.ts
export const select${pascal} = (s: RootState) => s.${camel}

export const selectAll${pascal} = createSelector(
  select${pascal},
  (slice: ${pascal}Slice) => slice.state
)

`,

    [`${kebab}-slice.ts`]: `// Auto-generated by pnpm addSlice ${name}
${importInitialState}
import { ${camel}Reducers } from "@/redux/${kebab}/${kebab}-reducers"
import { createAppSlice } from "@/redux/create-app-slice"

// If you are not using async thunks you can use the standalone \`createSlice\`.
export const ${camel}Slice = createAppSlice({
  name: "${camel}",
  initialState: ${camel}InitialState,
  reducers: (create) => ({
    reset${pascal}: create.reducer((state) => {
      // console.log("reducer reset state", state)
      state = ${camel}InitialState
      state.status = ${camel}InitialState.status
    }),
  }),
  extraReducers: () => ${camel}Reducers,
  selectors: {
    select${pascal}: (slice) => slice.state,
    select${pascal}Status: (slice) => slice.status,
  },
})

export const { reset${pascal} } = ${camel}Slice.actions

export const { select${pascal}, select${pascal}Status } = ${camel}Slice.selectors

`,

    [`${kebab}-thunks.ts`]: `// Auto-generated by pnpm addSlice ${name}
import { createAsyncThunk } from "@reduxjs/toolkit";

// Example thunk (rename/remove/extend as needed)
export const fetch${pascal} = createAsyncThunk(
  "${sliceName}/fetch",
  async (_arg: void, _api) => {
    // const { dispatch, getState, signal, rejectWithValue } = _api;
    // dispatch(setLoading());
    // const res = await fetch("/api/${kebab}", { signal });
    // if (!res.ok) return rejectWithValue(await res.json());
    // const data = await res.json();
    // dispatch(setSucceeded());
    // return data as unknown;
    return null;
  }
);
`,
    [`${kebab}-types.ts`]: `// Auto-generated by add-slice
import { RootSlice } from "@/redux/types"

export type ${pascal} = {
  id: string
  // add your slice data here
}

export type ${pascal}Slice = RootSlice<${pascal}>
`,
  }
}

async function pathExists(p) {
  try {
    await access(p, fsConstants.F_OK)
    return true
  } catch {
    return false
  }
}

async function main() {
  const { name, opts } = parseArgs(process.argv)

  if (!/^[a-zA-Z0-9-_]+$/.test(name)) {
    console.error(
      "❌ Name must contain only letters, numbers, hyphens or underscores."
    )
    process.exit(1)
  }

  const kebab = toKebab(name)
  const destDir = path.resolve(process.cwd(), opts.dir, kebab)

  if (await pathExists(destDir)) {
    console.error(`❌ Slice directory already exists: ${destDir}`)
    process.exit(1)
  }

  const files = templatesFor(name)
  console.log(`\n🧩 Creating Redux slice "${kebab}" in ${destDir}`)
  if (opts.dry) {
    console.log("🚫 Dry run. Files that would be created:")
    Object.keys(files).forEach((f) => console.log(`  - ${f}`))
    process.exit(0)
  }

  await mkdir(destDir, { recursive: true })
  await Promise.all(
    Object.entries(files).map(([file, content]) =>
      writeFile(path.join(destDir, file), content, "utf8")
    )
  )

  console.log("✅ Done!")
  console.log(`
Next steps:
1) Add reducer to your store (example):

   // src/store.ts
   import { configureStore } from "@reduxjs/toolkit";
   import { ${toCamel(name)}Reducer } from "./features/${kebab}/${kebab}-slice";

   export const store = configureStore({
     reducer: {
       ${toCamel(name)}: ${toCamel(name)}Reducer,
     },
   });

   export type RootState = ReturnType<typeof store.getState>;
   export type AppDispatch = typeof store.dispatch;

2) Update the RootState import in ${kebab}-selectors.ts if your store path differs.
`)
}

main().catch((err) => {
  console.error("❌ Unexpected error:", err)
  process.exit(1)
})
